const APP_VERSION='1.0.0';
const DEFAULT_REPOSITORY='Border55-repo/Korpsbrev';
let latestUpdate=null,updateBusy=false;
function repository(){const v=el('update-repo').value.trim().replace(/^https:\/\/github.com\//,'').replace(/\/$/,'');return /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(v)?v:null;}
function newer(a,b){if(!/^\d+\.\d+\.\d+$/.test(a)||!/^\d+\.\d+\.\d+$/.test(b))return false;const x=a.split('.').map(Number),y=b.split('.').map(Number);for(let i=0;i<3;i++){if(x[i]!==y[i])return x[i]>y[i];}return false;}
async function githubFetch(repo,path){const control=new AbortController(),timeout=setTimeout(()=>control.abort(),15000);try{const response=await fetch(`https://api.github.com/repos/${repo}/contents/${path}`,{headers:{Accept:'application/vnd.github.raw+json'},credentials:'omit',cache:'no-store',signal:control.signal});if(!response.ok){if(response.status===404)throw Error('Oppdateringskilden er ikke tilgjengelig. Prosjektet må være opprettet og offentlig for sjekk uten innlogging.');if(response.status===403||response.status===429)throw Error('GitHub begrenser forespørsler akkurat nå. Prøv igjen senere.');throw Error('Kunne ikke hente oppdateringen fra GitHub.');}return await response.text();}finally{clearTimeout(timeout);}}
async function checkUpdates(manual=false){if(updateBusy)return;const repo=repository();if(!repo){if(manual)toast('Skriv GitHub-prosjektet som brukernavn/prosjektnavn.');return;}updateBusy=true;el('update-check').disabled=true;el('update-status').textContent='Ser etter oppdateringer …';el('update-download').classList.add('hidden');latestUpdate=null;try{const raw=await githubFetch(repo,'version.json'),m=JSON.parse(raw);if(m.app!=='korpsbrev'||!/^\d+\.\d+\.\d+$/.test(m.version)||m.file!=='Korpsbrev.html'||!/^[a-f0-9]{64}$/.test(m.sha256))throw Error('Oppdateringsinformasjonen er ugyldig.');if(newer(m.version,APP_VERSION)){latestUpdate={...m,repo};el('update-status').textContent='Versjon '+m.version+' er tilgjengelig.';el('update-download').classList.remove('hidden');el('update-download').textContent='Last ned versjon '+m.version;el('update-panel').open=true;toast('En ny versjon av Korpsbrev er tilgjengelig.');}else{el('update-status').textContent='Du har nyeste tilgjengelige versjon ('+APP_VERSION+').';if(manual)toast('Du har nyeste tilgjengelige versjon.');}}catch(e){el('update-status').textContent=e.name==='AbortError'?'Sjekken tok for lang tid. Du kan fortsette å skrive.':e instanceof SyntaxError?'GitHub ga et uventet svar. Prøv igjen senere.':e.message==='Failed to fetch'?'Kunne ikke koble til GitHub. Du kan bruke verktøyet uten nett.':e.message;}finally{updateBusy=false;el('update-check').disabled=false;}}
el('update-repo').value=DEFAULT_REPOSITORY;
try{const saved=localStorage.getItem('korpsbrev-updates');if(saved){const v=JSON.parse(saved);if(typeof v.repo==='string')el('update-repo').value=v.repo;el('update-auto').checked=v.auto!==false;}}catch{}
function saveUpdateSettings(){try{localStorage.setItem('korpsbrev-updates',JSON.stringify({repo:el('update-repo').value,auto:el('update-auto').checked}));}catch{}}
el('update-repo').onchange=()=>{saveUpdateSettings();latestUpdate=null;el('update-download').classList.add('hidden');el('update-status').textContent='Trykk «Se etter oppdateringer» for å kontrollere kilden.';};el('update-auto').onchange=saveUpdateSettings;el('update-check').onclick=()=>checkUpdates(true);
el('update-download').onclick=async()=>{if(!latestUpdate)return;if(dirty){toast('Lagre brevet først med «Lagre brev», og trykk deretter på oppdateringen igjen.');return;}const u=latestUpdate,button=el('update-download');button.disabled=true;try{const html=await githubFetch(u.repo,'Korpsbrev.html');const bytes=new TextEncoder().encode(html);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==u.sha256)throw Error('Filkontrollen feilet. Ingen oppdatering ble lastet ned. Prøv en ny oppdateringssjekk.');if(!html.includes('name="korpsbrev-version" content="'+u.version+'"'))throw Error('Filen har feil versjonsnummer.');download(new Blob([bytes],{type:'text/html;charset=utf-8'}),'Korpsbrev-'+u.version+'.html');el('update-status').textContent='Oppdateringen er lastet ned. Åpne den nye HTML-filen og bruk «Åpne brev» for å fortsette med brevfilen din.';toast('Åpne den nye filen fra Nedlastinger.');}catch(e){toast(e.name==='AbortError'?'Nedlastingen tok for lang tid. Prøv igjen.':e.message);}finally{button.disabled=false;}};
if(el('update-auto').checked)setTimeout(()=>checkUpdates(false),1800);
